MyQ integration is failing to autheticate.
This issue has been opened: https://github.com/arraylabs/pymyq/issues/22
